apiVersion: v1
kind: Service
metadata:
  name: flask-minishift-docker      
spec:
  selector:                  
    deploymentconfig: flask-minishift-docker
  ports:
  - name: 8080-tcp
    port: 8080               
    protocol: TCP
    targetPort: 8080         